# Simple control file that loads additional modules as needed.
#
# To enable modules, place them in ~/dotfiles/zsh/modules-available/
# directory and symlink them into ~/dotfiles/zsh/modules-enabled/

set bell-style visible

# Load all enabled modules
for file in ~/dotfiles/zsh/modules/*; do
  source $file
done

SAVEHIST=500
HISTFILE=~/.zsh_history

# Java
export MAVEN_OPTS="-Xmx256m"
export HEAP="-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home"
export ANDROID_HOME="/Users/eugene/Library/Android/sdk"
export ANDROID_SDK="/Users/eugene/Library/Android/sdk"

export LDFLAGS="-L/usr/local/opt/ncurses/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include"

export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"

# Node
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

[[ -s /Users/$USER/.nvm/nvm.sh ]] && . /Users/$USER/.nvm/nvm.sh
export PATH="$PATH:/usr/local/opt/ncurses/bin"
export PATH="$PATH:/Users/eugene/Library/Python/3.7/bin"
export PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools"
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="/Users/eugene/Library/Python/3.7/bin:$PATH"
export PATH="$PATH:./node_modules/.bin"
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export NVM_DIR="$HOME/.nvm"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/elee/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/elee/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/elee/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/elee/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
=======
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/eugenelee/.sdkman"
[[ -s "/Users/elee/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/elee/.sdkman/bin/sdkman-init.sh"
