# Simple control file that loads additional modules as needed.
#
# To enable modules, place them in ~/dotfiles/zsh/modules-available/
# directory and symlink them into ~/dotfiles/zsh/modules-enabled/

set bell-style visible

# Load all enabled modules
for file in ~/dotfiles/zsh/modules/*; do
  source $file
done

SAVEHIST=500
HISTFILE=~/.zsh_history

# AWS
export AWS_PROFILE=elee

# Java
export MAVEN_OPTS="-Xmx1024m"
export HEAP="-Xms2g -Xmx2g -XX:MaxMetaspaceSize=1024m"
export JAVA_HOME="/Users/elee/.sdkman/candidates/java/current/jre"
export ANDROID_HOME="/Users/elee/Library/Android/sdk"
export ANDROID_SDK="/Users/elee/Library/Android/sdk"

export LDFLAGS="-L/usr/local/opt/ncurses/lib -L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include -I/usr/local/opt/icu4c/include"

# Node
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
[[ -s /Users/$USER/.nvm/nvm.sh ]] && . /Users/$USER/.nvm/nvm.sh


export PATH="$PATH:/usr/local/opt/ncurses/bin"
export PATH="$PATH:/opt/homebrew/Cellar/python@3.11/3.11.4"
export PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools"
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:./node_modules/.bin"
export PATH="/usr/local/opt:$PATH"
export NVM_DIR="$HOME/.nvm"

# Ruby
#eval "$(rbenv init - zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/elee/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/elee/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/elee/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/elee/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
export PATH="/usr/local/opt/openssl@3/bin:$PATH"
export PATH="$HOME/.jenv/bin:$PATH"
#eval "$(jenv init -)"
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/elee/.sdkman"
[[ -s "/Users/elee/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/elee/.sdkman/bin/sdkman-init.sh"

eval "$(/opt/homebrew/bin/brew shellenv)"
