# Simple control file that loads additional modules as needed.
#
# To enable modules, place them in ~/dotfiles/zsh/modules-available/
# directory and symlink them into ~/dotfiles/zsh/modules-enabled/

# Load all enabled modules
for file in ~/dotfiles/zsh/modules/*; do
  source $file
done

SAVEHIST=500
HISTFILE=~/.zsh_history

export MAVEN_OPTS="-Xmx256m"
export LDFLAGS="-L/usr/local/opt/ncurses/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

[[ -s /Users/$USER/.nvm/nvm.sh ]] && . /Users/$USER/.nvm/nvm.sh
export PATH="$PATH:/usr/local/opt/ncurses/bin"
export PATH="$PATH:/Users/eugene/Library/Python/3.7/bin"
